### ISSUE TITLE
Project doesnt compile with swift 3.0.1

### ISSUE THREAD

**Issue by pikaboo** [nschum/SwiftHamcrest#26]
```
Showing All Messages
CompileSwift normal x86_64 
                              _ 
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/Hamcrest.swift:8:68: error: function types cannot have argument label 'line'; use '_' instead
public var HamcrestReportFunction: (_: String, file: StaticString, line: UInt) -> () = HamcrestDefaultReportFunction
                                                                   ^
                                                                   _ 
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/ReflectionMatchers.swift:29:39: error: expected ',' joining parts of a multi-clause condition
        if let label = property.label where keyMatcher.matches(label) {
                                     ~^~~~~
                                     ,
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/ArithmeticMatchers.swift:34:30: error: 'IntervalType' is unavailable: IntervalType has been removed in Swift 3. Use ranges instead.
public func inInterval<T, I: IntervalType where I.Bound == T>(expectedInterval: I) -> Matcher<T> {
                             ^~~~~~~~~~~~
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/ArithmeticMatchers.swift:34:51: error: 'Bound' is not a member type of 'I'
public func inInterval<T, I: IntervalType where I.Bound == T>(expectedInterval: I) -> Matcher<T> {
                                                ~ ^
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/MatchResult.swift:1:53: error: 'BooleanType' has been renamed to 'Bool'
public enum MatchResult: BooleanLiteralConvertible, BooleanType {
                                                    ^~~~~~~~~~~
                                                    Bool
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/Matcher.swift:6:45: error: single argument function types require parentheses
    public init(_ description: String, _ f: T -> MatchResult) {
                                            ^
                                            ()
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/Matcher.swift:11:45: error: single argument function types require parentheses
    public init(_ description: String, _ f: T -> Bool) {
                                            ^
                                            ()
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/ArithmeticMatchers.swift:14:19: error: argument labels '(_:, _:)' do not match any available overloads
    let matcher = closeTo(Double(expectedValue), delta)
                  ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/ArithmeticMatchers.swift:14:19: note: overloads for 'closeTo' exist with these partially matching parameter lists: (expectedValue: Double, Double), (expectedValue: Float, Double)
    let matcher = closeTo(Double(expectedValue), delta)
                  ^
/Users/projectlocation/Pods/SwiftHamcrest/Hamcrest/ArithmeticMatchers.swift:35:56: error: value of type 'I' has no member 'contains'
    return Matcher("in interval \(expectedInterval)") {expectedInterval.contains($0)}
                                                       ^~~~~~~~~~~~~~~~ ~~~~~~~~


```

**Comment by renep** [comment]
It compiles on my machine. I have tried it it Xcode 8.3 and Swift 3.1.
